### ISSUE TITLE
libev download fails

### ISSUE THREAD

**Issue by witaly-iwanow** [ibm-security-innovation/goldy#12]
make deps output:
```
tar xzf mbedtls-2.7.10-apache.tgz
rm -f mbedtls-2.7.10-apache.tgz
Downloading libev-4.27 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error downloading libev: Check the LIBEV_VER in deps/versions.mk and current version in http://dist.schmorp.de/libev/
Makefile:30: recipe for target 'download_libev' failed
make[1]: *** [download_libev] Error 1
```

**Comment by witaly-iwanow** [comment]
the fix is pretty obvious, but still... You need to point to http://dist.schmorp.de/libev/Attic/libevXYZ.tgz, if you want to avoid fixing it every time new version of libev is released.
I can provide a PR if someone is around to merge it

**Comment by dubek** [comment]
You're right, a link to `Attic` would be a more stable idea.
I can review and merge a PR (try to update to latest libev as well).

**Comment by witaly-iwanow** [comment]
Done. I was playing around with it a few hours ago, and libev was at 4.31. All of a sudden it was updated to 4.33, found out by accident, had to add an extra commit.
Great little proxy btw, neat job!

**Comment by dubek** [comment]
Done in #13. Closing.
