### ISSUE TITLE
Error downloading libev

### ISSUE THREAD

**Issue by testcaoy7** [ibm-security-innovation/goldy#2]
After running "make deps", mbedTLS was downloaded successfully and libev cannot be downloaded.

Downloading libev-4.22 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error downloading libev: Check the LIBEV_VER in deps/versions.mk and current version in http://dist.schmorp.de/libev/
Makefile:30: recipe for target 'download_libev' failed
make[1]: *** [download_libev] Error 1
make[1]: Leaving directory '/root/goldy/deps'
Makefile:99: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by testcaoy7** [comment]
I solved this problem. Just change deps/versions.mk where "LIBEV_VER=4.22" to "LIBEV_VER=4.23"

**Comment by guyannanfei25** [comment]
yes, libev version changes frequently

**Comment by dubek** [comment]
I pushed a new `deps/versions.mk` which uses latest versions of libev and mbedtls.

**Comment by testcaoy7** [comment]
@dubek Thank you! However, can you make goldy accept SOCKS5 so that almost all programs that support proxy setting can use goldy as a secure tunnel.
